

logging:
  path: /data/logs/auth-server/
  level:
   root: INFO
   org:
    springframework:
      security: INFO
      org.springframework.web: INFO
    com.econetwireless.credit: INFO

  file:  /data/logs/auth-server/application.log

server:
  port: 8189
  servlet:
    context-path: /@project.artifactId@/api

spring:
  datasource:
    url: jdbc:mysql://139.84.231.40:3306/auth_service_db?useSSL=false
    username: root
    password: '#Letmein123'
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
  application:
    name: authentication-handler
keyFile: auth-server.jks
password: '#pass123'
alias: auth-server